apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-application
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-application
  template:
    metadata:
      labels:
        app: devops-application
    spec:
      containers:
        - name: devops-application
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            