apiVersion: v1
kind: Service
metadata:
  name: devops-application
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-application
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      